// ===================================================================
//  הגדרות האפליקציה  —  ניתן לעריכה בלי ידע בתכנות
// ===================================================================
window.APP_CONFIG = {

  // גרסת קבצים — נוספת לקישורי ההורדה כדי לעקוף קאש של הדפדפן. יש להעלות בכל החלפת קובץ.
  assetVersion: "20260619a",

  // כתובות המייל של חברי הוועדה שיקבלו גישת ניהול (רואים את כל המשתתפים).
  // יש להקפיד על אותיות קטנות.
  adminEmails: [
    "jude@excelleader.co.il"
  ],

  // טקסט הסבר למסך התבניות (טאב 2).
  templatesIntro: "אלו תבניות מומלצות שאתם מוזמנים להשתמש בהן בעבודתכם המקצועית. מומלץ להעתיק את התוכן ולעצב אותו על נייר הלוגו שלכם. השימוש בתבניות הוא רשות.",

  // תבניות להורדה (טאב 2). הקבצים יושבים בתיקייה templates/ של האפליקציה.
  templates: [
    { file: "מדריך Best Practice ליועץ עסקי.pdf", title: "מדריך Best Practice ליועץ עסקי", desc: "חומר עזר מקצועי מלא (PDF)" },
    { file: "תבנית דוח אבחון מקצועי.docx", title: "תבנית דוח אבחון מקצועי", desc: "מבנה מומלץ לדוח אבחון" },
    { file: "תבנית דוח המלצות מקצועי.docx", title: "תבנית דוח המלצות מקצועי", desc: "מבנה מומלץ לדוח המלצות" },
    { file: "מה צריכה להכיל תכנית עסקית.docx", title: "מה צריכה להכיל תכנית עסקית", desc: "מבנה מומלץ לתכנית עסקית" }
  ],

  // מסמכים שהמשתתף נדרש להעלות (טאב 1).
  requiredUploads: [
    { id: "cv", title: "קורות חיים מפורטים", short: "קו״ח", desc: "כולל תיאורי פרויקטים להוכחת ניסיון ומומחיות" },
    { id: "certificates", title: "תעודות מקצועיות", short: "תעודות", desc: "ניתן להעלות כמה קבצים" },
    { id: "clientRefs", title: "שלוש המלצות מלקוחות", short: "המלצות", desc: "מכתבי המלצה או פרטי ממליצים" },
    { id: "finalExercise", title: "תרגיל מסכם (עבודת צוות)", short: "תרגיל מסכם", desc: "העלו את הקובץ הסופי של התרגיל המסכם. כל חבר צוות מעלה את הקובץ המשותף." }
  ],

  // סדר הפריטים במסך ההסמכה (טאב 1). kind: form / upload / download.
  certItems: [
    { kind: "download", file: "קוד המקצוע לייעוץ עסקי של לשכת היועצים העסקיים בישראל.pdf", title: "קוד המקצוע", desc: "מסמך קוד המקצוע של הלשכה (PDF) — להורדה ולקריאה" },
    { kind: "form", id: "selfAssessCompetence" },
    { kind: "form", id: "projectExperience" },
    { kind: "upload", id: "cv" },
    { kind: "upload", id: "certificates" },
    { kind: "upload", id: "clientRefs" },
    { kind: "form", id: "processUnderstanding" },
    { kind: "download", file: "תרגיל סופי להסמכה - יישום קוד המקצוע.docx", title: "תרגיל מסכם להסמכה", desc: "כתב המשימה של התרגיל המסכם (עבודת צוות 2-3) — להורדה" },
    { kind: "upload", id: "finalExercise" },
    { kind: "form", id: "declaration" }
  ],

  // טפסים שממלאים וחותמים בתוך האפליקציה.
  forms: [
    {
      id: "declaration",
      title: "כתב התחייבות ליישום קוד המקצוע",
      short: "התחייבות",
      subtitle: "לחתימה בתום הדרכת ההסמכה",
      intro: "אני הח״מ מצהיר/ה ומתחייב/ת בזאת, מרצוני החופשי, כי איישם בעבודתי השוטפת את עקרונות קוד מקצוע היועץ העסקי של לשכת היועצים העסקיים בישראל, כמפורט להלן:",
      fields: [
        { id: "fullName", label: "שם מלא", type: "text", required: true },
        { id: "idNumber", label: "מספר תעודת זהות", type: "text", required: true },
        { id: "certNumber", label: "מספר הסמכה (אם קיבלת בעבר)", type: "text", required: false }
      ],
      commitments: [
        "אפעל על-פי קוד מקצוע היועץ העסקי של לשכת היועצים העסקיים בישראל, ואיישם את עקרונותיו בכל התקשרות מקצועית.",
        "אנהל את תהליך הייעוץ בהתאם לקוד המקצוע (שלבי התקשרות, ביצוע וסגירה), תוך הבנת הקשר הלקוח, ניהול סיכונים ויצירת ערך.",
        "אעמיד את טובת הלקוח ואת יצירת הערך המדיד ובר-הקיימא במרכז עבודתי.",
        "אשמור על התנהגות אתית, יושרה, אובייקטיביות ואי-תלות מקצועית.",
        "אשמור על סודיות מידע הלקוח, על הגנת הפרטיות ועל קניין רוחני, אגלה כל ניגוד עניינים אפשרי ואמנע ממנו.",
        "אגדיר בבירור מול הלקוח את היקף העבודה, המטרות, המתודולוגיה, התנאים והתוצרים בכל התקשרות.",
        "אקיים תקשורת שקופה, כנה ואפקטיבית עם הלקוח ועם בעלי העניין לאורך הפרויקט.",
        "אבסס את המלצותיי על נתונים, ניתוח מקצועי ושיקול דעת ענייני.",
        "אתמיד בפיתוח מקצועי מתמשך (CPD) ובעדכון שוטף של הידע, הכלים והמתודולוגיות שלי.",
        "אפעל בהתאם לתקנון, לכללי האתיקה ולערכי הלשכה, ואשמור על כבוד המקצוע ומעמדו."
      ],
      confirmText: "קראתי את ההתחייבויות לעיל ואני מתחייב/ת לפעול לפיהן.",
      closing: "ידוע לי כי יישום עקרונות הקוד הוא תנאי לקבלת ההסמכה ולשמירתה.",
      requireSignature: true
    },

    {
      id: "selfAssessCompetence",
      title: "הערכה עצמית לפי מסגרת הכשירויות IBCA",
      short: "הע׳ כשירויות",
      subtitle: "דרגו את עצמכם בכל כישור. ניתן לשמור ולעדכן בכל עת.",
      requireSignature: true,
      confirmText: "קראתי את ההצהרה לעיל, ואני מאשר/ת ומצהיר/ה כאמור.",
      items: [
        { type: "info", text: "סולם הדירוג: 1 בסיסי · 2 מתחיל · 3 בינוני · 4 מתקדם · 5 מומחה · 0 לא מכיר כלל. ענו בכנות, זה יעזור לזהות תחומי פיתוח." },
        { type: "section", label: "פרטים אישיים" },
        { type: "text", id: "fullName", label: "שם מלא", required: true },
        { type: "text", id: "yearsExp", label: "שנות ניסיון בייעוץ" },
        { type: "text", id: "specialty", label: "תחום התמחות עיקרי" },
        { type: "section", label: "1. הבנה עסקית" },
        { type: "section", level: 3, label: "1.1 ידע מקצועי בתחומי הניהול" },
        { type: "checkboxes", id: "mgmtAreas", label: "תחומי ידע מרכזיים (סמנו את שלכם):", other: true, options: ["ניהול אסטרטגי","ניהול משאבי אנוש","ניהול פיננסי","ניהול שיווק ומכירות","ניהול תפעול","ניהול טכנולוגיה","ניהול סיכונים","ניהול לוגיסטי","ניהול מערכות מידע","ניהול מערכות תקינה","לא מכיר אף אחד מאלה"] },
        { type: "section", level: 3, label: "1.2 הבנה ארגונית" },
        { type: "rating", id: "orgStructure", label: "ניתוח מבנה ארגוני", zero: true },
        { type: "rating", id: "orgCulture", label: "הבנת תרבות ארגונית", zero: true },
        { type: "rating", id: "powerDynamics", label: "זיהוי דינמיקות כוח", zero: true },
        { type: "rating", id: "decisionMaking", label: "הבנת תהליכי קבלת החלטות", zero: true },
        { type: "textarea", id: "orgExample", label: "דוגמה מפרויקט שבו ניתחתם ארגון" },
        { type: "section", level: 3, label: "1.3 הבנה שיווקית" },
        { type: "checkboxes", id: "marketingAreas", label: "תחומי יכולת (סמנו):", other: true, options: ["ניתוח שוק ותחרות","פילוח לקוחות","אסטרטגיות שיווק","ניתוח התנהגות צרכנים","שיווק דיגיטלי","מחקר שוק","לא מכיר אף אחד מאלה"] },
        { type: "textarea", id: "marketingExample", label: "איך השתמשתם בידע שיווקי בפרויקט ייעוץ" },
        { type: "section", level: 3, label: "1.4 חשיבה אסטרטגית" },
        { type: "rating", id: "longTerm", label: "ראייה ארוכת טווח", zero: true },
        { type: "rating", id: "systemic", label: "חשיבה מערכתית", zero: true },
        { type: "rating", id: "oppThreats", label: "זיהוי הזדמנויות ואיומים", zero: true },
        { type: "rating", id: "deepAnalysis", label: "יכולת ניתוח מעמיק", zero: true },
        { type: "rating", id: "creativeThink", label: "חשיבה יצירתית", zero: true },
        { type: "textarea", id: "strategicExample", label: "תארו פרויקט שדרש חשיבה אסטרטגית" },
        { type: "section", level: 3, label: "1.5 אוריינות פיננסית" },
        { type: "checkboxes", id: "finAreas", label: "יכולות פיננסיות (סמנו):", other: true, options: ["קריאת דוחות כספיים","ניתוח יחסים פיננסיים","הערכת השקעות (ROI, NPV)","תכנון תקציב","ניתוח עלות-תועלת","מודלים פיננסיים","לא מכיר אף אחד מאלה"] },
        { type: "textarea", id: "finExample", label: "דוגמה לשימוש בכלים פיננסיים בייעוץ" },
        { type: "section", level: 3, label: "1.6 העולם הרגולטורי" },
        { type: "checkboxes", id: "regAreas", label: "היכרות עם תחומים רגולטוריים (סמנו):", other: true, options: ["דיני עבודה","דיני חברות","רגולציה פיננסית","הגנת הצרכן","דיני התחרות (הגבלים עסקיים)","הגנת הפרטיות (GDPR)","תקנות איכות סביבה","תקני איכות (ISO, HACCP)","תקני סייבר","תקני הפצת מידע","FDA / CE / משרד הבריאות / תקני מזון","לא מכיר אף אחד מאלה"] },
        { type: "textarea", id: "regExample", label: "איך התמודדתם עם סוגיה רגולטורית בפרויקט" },
        { type: "section", label: "2. מיומנויות ייעוץ" },
        { type: "section", level: 3, label: "2.1 ניתוח בעיות" },
        { type: "checkboxes", id: "analysisTools", label: "כלי ניתוח שאתם משתמשים בהם (סמנו):", other: true, options: ["5 Whys","Root Cause Analysis","Fishbone Diagram","SWOT","Porter's 5 Forces","Value Chain Analysis","Gap Analysis","לא מכיר אף אחד מאלה"] },
        { type: "textarea", id: "problemExample", label: "תארו בעיה מורכבת שפתרתם ואיך" },
        { type: "section", level: 3, label: "2.2 פיתוח פתרונות" },
        { type: "rating", id: "creativity2", label: "חשיבה יצירתית", zero: true },
        { type: "rating", id: "alternatives", label: "פיתוח אלטרנטיבות", zero: true },
        { type: "rating", id: "feasibility", label: "הערכת כדאיות", zero: true },
        { type: "rating", id: "orgFit", label: "התאמה לארגון", zero: true },
        { type: "rating", id: "implementationCap", label: "יכולת יישום", zero: true },
        { type: "textarea", id: "solutionExample", label: "דוגמה לפתרון חדשני שפיתחתם" },
        { type: "section", level: 3, label: "2.3 ניהול פרויקטים" },
        { type: "checkboxes", id: "pmTools", label: "כלי ושיטות ניהול פרויקטים (סמנו):", other: true, options: ["MS Project / Asana / Monday","Gantt Charts","PERT/CPM","Agile/Scrum","Risk Management","Stakeholder Management","לא מכיר אף אחד מאלה"] },
        { type: "text", id: "bigProjBudget", label: "הפרויקט הגדול ביותר שניהלתם — תקציב (ש\"ח)" },
        { type: "text", id: "bigProjDuration", label: "משך (חודשים)" },
        { type: "text", id: "bigProjTeam", label: "גודל צוות (אנשים)" },
        { type: "textarea", id: "bigProjDesc", label: "תיאור קצר" },
        { type: "section", level: 3, label: "2.4 ניהול שינויים" },
        { type: "checkboxes", id: "changeModels", label: "מודלי ניהול שינוי שאתם מכירים (סמנו):", other: true, options: ["Kotter's 8 Steps","ADKAR","Lean Change Management","Bridges Transition Model","McKinsey 7-S","לא מכיר אף אחד מאלה"] },
        { type: "textarea", id: "changeExample", label: "תארו תהליך שינוי מאתגר שהובלתם" },
        { type: "section", label: "3. מיומנויות בין-אישיות" },
        { type: "section", level: 3, label: "3.1 תקשורת" },
        { type: "rating", id: "presenting", label: "הצגה בפני קהל", zero: true },
        { type: "rating", id: "writing", label: "כתיבה מקצועית", zero: true },
        { type: "rating", id: "listening", label: "הקשבה פעילה", zero: true },
        { type: "rating", id: "nonverbal", label: "תקשורת לא מילולית", zero: true },
        { type: "rating", id: "simplify", label: "הסבר מורכבות בפשטות", zero: true },
        { type: "textarea", id: "presentingChallenge", label: "ההצגה הכי מאתגרת שעשיתם" },
        { type: "section", level: 3, label: "3.2 בניית מערכות יחסים" },
        { type: "rating", id: "trust", label: "בניית אמון מהיר", zero: true },
        { type: "rating", id: "networks", label: "רשתות מקצועיות", zero: true },
        { type: "rating", id: "longRelations", label: "ניהול קשרים ארוכי טווח", zero: true },
        { type: "rating", id: "seniors", label: "עבודה עם דרגים בכירים", zero: true },
        { type: "section", level: 3, label: "3.3 הנחיה ואימון" },
        { type: "checkboxes", id: "coachingExp", label: "ניסיון בהנחיה (סמנו):", other: true, options: ["הנחיית סדנאות","אימון מנהלים","הקמת צוותים","פיתוח עובדים","הכשרות מקצועיות"] },
        { type: "text", id: "coachedCount", label: "כמה אנשים אימנתם/הנחיתם בשנה האחרונה" },
        { type: "section", label: "4. תכונות אישיות" },
        { type: "section", level: 3, label: "4.1 יושרה ואתיקה" },
        { type: "textarea", id: "ethicsHandling", label: "איך אתם מטפלים בדילמות אתיות" },
        { type: "textarea", id: "principlesStood", label: "תארו מצב שבו עמדתם על העקרונות שלכם" },
        { type: "section", level: 3, label: "4.2 למידה מתמשכת" },
        { type: "checkboxes", id: "learningActivities", label: "פעילויות למידה בשנה האחרונה (סמנו):", other: true, options: ["קורסים מקצועיים","כנסים ואירועים","קריאה מקצועית","הסמכות חדשות","למידה עצמית"] },
        { type: "section", level: 3, label: "4.3 יכולת הסתגלות" },
        { type: "rating", id: "adaptability", label: "יכולת הסתגלות", zero: true },
        { type: "textarea", id: "adaptExample", label: "תארו מצב שבו נדרשתם להסתגל במהירות" },
        { type: "section", label: "5. מומחיות טכנית" },
        { type: "section", level: 3, label: "5.1 התמחות רלוונטית" },
        { type: "text", id: "mainField", label: "התחום הראשי שלכם" },
        { type: "text", id: "yearsInField", label: "שנות ניסיון בתחום" },
        { type: "rating", id: "expertiseLevel", label: "רמת המומחיות", zero: true },
        { type: "textarea", id: "fieldAchievements", label: "הישגים מרכזיים בתחום ההתמחות" },
        { type: "section", level: 3, label: "5.2 כלים ומתודולוגיות אנליטיים" },
        { type: "rating", id: "excelAdv", label: "Excel מתקדם", zero: true },
        { type: "rating", id: "biTools", label: "כלי BI (Tableau, PowerBI)", zero: true },
        { type: "rating", id: "processMapping", label: "Process Mapping", zero: true },
        { type: "rating", id: "dataMining", label: "Data Mining", zero: true },
        { type: "section", level: 3, label: "5.3 מודעות טכנולוגית" },
        { type: "checkboxes", id: "techAreas", label: "תחומי טכנולוגיה שאתם מכירים (סמנו):", other: true, options: ["Digital Transformation","Cloud Computing","AI & Machine Learning","Automation/RPA","Cybersecurity","IoT","Blockchain","לא מכיר אף אחד מאלה"] },
        { type: "section", level: 3, label: "5.4 חדשנות ויצירתיות" },
        { type: "textarea", id: "innovationExamples", label: "דוגמאות לחדשנות שהובלתם" },
        { type: "section", label: "סיכום והערכה כוללת" },
        { type: "textarea", id: "strengths", label: "5 נקודות החוזק המרכזיות שלכם" },
        { type: "textarea", id: "devAreas", label: "3 התחומים שהכי חשוב לכם לפתח" },
        { type: "textarea", id: "devPlan", label: "איך אתם מתכננים לפתח את עצמכם בשנה הקרובה" },
        { type: "rating", id: "overall10", label: "הערכת הכשירות הכוללת שלכם כיועץ מוסמך (1-10)", max: 10 },
        { type: "textarea", id: "overallReason", label: "נימוק להערכה" },
        { type: "section", label: "הצהרה" },
        { type: "info", text: "אני החתום/ה מטה מצהיר/ה כי מילאתי את טופס ההערכה העצמית לפי מסגרת הכשירויות של IBCA באופן כן, מדויק ומלא, למיטב ידיעתי והבנתי.\n\nידוע לי כי ההערכה העצמית נועדה לשקף את רמת כשירותי המקצועית הנוכחית, לסייע בזיהוי תחומי חוזקה ותחומי פיתוח, ולהוות חלק מתהליך ההסמכה וההתפתחות המקצועית.\n\nאני מתחייב/ת לפעול ביושרה, באחריות מקצועית, בשקיפות ובהגינות, לשמור על רמה מקצועית נאותה, להמשיך בלמידה ובהתפתחות מקצועית מתמשכת, ולפעול בהתאם לקוד המקצוע, לכללי האתיקה המקצועית ולהוראות כל דין רלוונטי.\n\nידוע לי כי מסירת מידע שאינו נכון או שאינו מלא עלולה להשפיע על בחינת זכאותי להסמכה או על המשך השתתפותי בתהליך." }
      ]
    },

    {
      id: "processUnderstanding",
      title: "אישור הבנת תהליכי העבודה לפי קוד המקצוע",
      short: "תהליכי העבודה",
      subtitle: "לקריאה ולאישור הבנה",
      requireSignature: true,
      confirmText: "קראתי והבנתי את הנחיות תהליך הייעוץ של הלשכה לפי קוד המקצוע, ואני מתחייב/ת לפעול לפיהן.",
      items: [
        { type: "info", text: "טופס זה מציג את הנחיות תהליך הייעוץ של הלשכה לפי קוד המקצוע. אנא קראו בעיון, אשרו את הבנתכם וחתמו." },
        { type: "section", label: "פרטים אישיים" },
        { type: "text", id: "fullName", label: "שם מלא", required: true },
        { type: "section", label: "1. התקשרות" },
        { type: "section", level: 3, label: "1.1 הבנת הקשר הלקוח" },
        { type: "statement", text: "ניתוח סביבת העסקים של הלקוח" },
        { type: "statement", text: "זיהוי בעלי עניין" },
        { type: "statement", text: "הערכת צרכי הלקוח וציפיותיו" },
        { type: "section", level: 3, label: "1.2 הצעה והסכם" },
        { type: "statement", text: "הגדרת היקף ומטרות" },
        { type: "statement", text: "תיאור המתודולוגיה והגישה" },
        { type: "statement", text: "קביעת תנאים והגבלות" },
        { type: "statement", text: "התייחסות להגנת הפרטיות, לקניין רוחני ושמירה על סודיות" },
        { type: "section", label: "2. ביצוע" },
        { type: "section", level: 3, label: "2.1 תכנון" },
        { type: "statement", text: "פיתוח תכנית פרויקט מפורטת" },
        { type: "statement", text: "הקצאת משאבים" },
        { type: "statement", text: "הקמת צוות ליבה" },
        { type: "statement", text: "זיהוי וצמצום סיכונים" },
        { type: "section", level: 3, label: "2.2 יישום" },
        { type: "statement", text: "איסוף וניתוח נתונים" },
        { type: "statement", text: "פיתוח פתרונות" },
        { type: "statement", text: "תקשורת ודיווח סדירים ללקוח" },
        { type: "statement", text: "ניהול שינויים והסתגלות לנסיבות חדשות" },
        { type: "section", level: 3, label: "2.3 אינטראקציה עם הלקוח" },
        { type: "statement", text: "סיוע במעורבות הלקוח" },
        { type: "statement", text: "ניהול ציפיות הלקוח" },
        { type: "statement", text: "הבטחת העברת ידע" },
        { type: "section", label: "3. סגירה" },
        { type: "section", level: 3, label: "3.1 מסירת תוצאות" },
        { type: "statement", text: "הצגת המלצות סופיות" },
        { type: "statement", text: "תיעוד תוצרים" },
        { type: "statement", text: "תמיכה ביישום (אם רלוונטי)" },
        { type: "section", level: 3, label: "3.2 הערכה" },
        { type: "statement", text: "הערכת תוצאות הפרויקט" },
        { type: "statement", text: "איסוף משוב מהלקוח" },
        { type: "statement", text: "ביצוע סקירה פנימית ולקחים נלמדים" },
        { type: "section", level: 3, label: "3.3 סגירה אדמיניסטרטיבית" },
        { type: "statement", text: "סיום תיעוד" },
        { type: "statement", text: "טיפול בסוגיות תלויות ועומדות" },
        { type: "statement", text: "סגירה רשמית של ההתקשרות" },
        { type: "section", label: "4. עקרונות מנחים" },
        { type: "section", level: 3, label: "4.1 התנהגות אתית" },
        { type: "statement", text: "דבקות בקוד המקצוע של הלשכה" },
        { type: "statement", text: "ניהול ניגודי אינטרסים" },
        { type: "section", level: 3, label: "4.2 כשירות מקצועית" },
        { type: "statement", text: "מומחיות מוכחת מתאימה לתחום ההתמחות הנדרש להתקשרות" },
        { type: "statement", text: "למידה ושיפור מתמשכים: השתתפות בקורסים/השתלמויות חובה" },
        { type: "section", level: 3, label: "4.3 תקשורת" },
        { type: "statement", text: "תקשורת ברורה ובזמן עם לקוחות" },
        { type: "statement", text: "תקשורת פנימית יעילה בצוות" },
        { type: "section", level: 3, label: "4.4 יצירת ערך" },
        { type: "statement", text: "התמקדות במתן ערך בר-קיימא ללקוח" },
        { type: "statement", text: "איזון בין תועלות קצרות טווח וארוכות טווח" }
      ]
    },

    {
      id: "projectExperience",
      title: "תיאור פרויקטי ייעוץ",
      short: "פרויקטים",
      subtitle: "תיאור קצר של פרויקטים מייצגים להוכחת הניסיון המקצועי. ניתן לשמור ולעדכן בכל עת.",
      requireSignature: true,
      confirmText: "קראתי את ההצהרה לעיל, ואני מאשר/ת ומצהיר/ה כאמור.",
      items: [
        { type: "info", text: "תארו 2–3 פרויקטים מייצגים מהשנים האחרונות, שמדגימים את הניסיון שלכם ואת סוגי הפרויקטים שאתם מבצעים. אין צורך בפירוט מתודולוגי. חשוב: השמיטו כל פרט שעלול לזהות את הלקוח או לפגוע בסודיות עסקית." },
        { type: "section", label: "פרטים אישיים" },
        { type: "text", id: "fullName", label: "שם מלא", required: true },
        { type: "text", id: "yearsExp", label: "שנות ניסיון בייעוץ" },

        { type: "section", label: "פרויקט 1" },
        { type: "text", id: "p1_name", label: "שם קודי לפרויקט (ללא פרטים מזהים)", required: true },
        { type: "text", id: "p1_sector", label: "ענף / תחום הלקוח" },
        { type: "text", id: "p1_period", label: "תקופת ביצוע ומשך (לדוגמה: 03/2024–09/2024, 6 חודשים)" },
        { type: "checkboxes", id: "p1_role", label: "תפקידך בפרויקט:", other: true, options: ["יועץ ראשי / מנהל פרויקט","יועץ בכיר בצוות","יועץ מומחה בתחום ספציפי"] },
        { type: "textarea", id: "p1_desc", label: "תיאור הפרויקט וההישגים המרכזיים (כולל תוצאות מדידות, אם יש)", required: true },
        { type: "info", text: "פרטו 2–3 אתגרים מרכזיים בפרויקט ואת הפתרון שהצעתם לכל אחד:" },
        { type: "textarea", id: "p1_ch1", label: "אתגר מרכזי 1" },
        { type: "textarea", id: "p1_sol1", label: "הפתרון שהוצע לאתגר 1" },
        { type: "textarea", id: "p1_ch2", label: "אתגר מרכזי 2" },
        { type: "textarea", id: "p1_sol2", label: "הפתרון שהוצע לאתגר 2" },
        { type: "textarea", id: "p1_ch3", label: "אתגר מרכזי 3 (אופציונלי)" },
        { type: "textarea", id: "p1_sol3", label: "הפתרון שהוצע לאתגר 3 (אופציונלי)" },

        { type: "section", label: "פרויקט 2" },
        { type: "text", id: "p2_name", label: "שם קודי לפרויקט (ללא פרטים מזהים)" },
        { type: "text", id: "p2_sector", label: "ענף / תחום הלקוח" },
        { type: "text", id: "p2_period", label: "תקופת ביצוע ומשך (לדוגמה: 03/2024–09/2024, 6 חודשים)" },
        { type: "checkboxes", id: "p2_role", label: "תפקידך בפרויקט:", other: true, options: ["יועץ ראשי / מנהל פרויקט","יועץ בכיר בצוות","יועץ מומחה בתחום ספציפי"] },
        { type: "textarea", id: "p2_desc", label: "תיאור הפרויקט וההישגים המרכזיים (כולל תוצאות מדידות, אם יש)" },
        { type: "info", text: "פרטו 2–3 אתגרים מרכזיים בפרויקט ואת הפתרון שהצעתם לכל אחד:" },
        { type: "textarea", id: "p2_ch1", label: "אתגר מרכזי 1" },
        { type: "textarea", id: "p2_sol1", label: "הפתרון שהוצע לאתגר 1" },
        { type: "textarea", id: "p2_ch2", label: "אתגר מרכזי 2" },
        { type: "textarea", id: "p2_sol2", label: "הפתרון שהוצע לאתגר 2" },
        { type: "textarea", id: "p2_ch3", label: "אתגר מרכזי 3 (אופציונלי)" },
        { type: "textarea", id: "p2_sol3", label: "הפתרון שהוצע לאתגר 3 (אופציונלי)" },

        { type: "section", label: "פרויקט 3 (אופציונלי)" },
        { type: "text", id: "p3_name", label: "שם קודי לפרויקט (ללא פרטים מזהים)" },
        { type: "text", id: "p3_sector", label: "ענף / תחום הלקוח" },
        { type: "text", id: "p3_period", label: "תקופת ביצוע ומשך (לדוגמה: 03/2024–09/2024, 6 חודשים)" },
        { type: "checkboxes", id: "p3_role", label: "תפקידך בפרויקט:", other: true, options: ["יועץ ראשי / מנהל פרויקט","יועץ בכיר בצוות","יועץ מומחה בתחום ספציפי"] },
        { type: "textarea", id: "p3_desc", label: "תיאור הפרויקט וההישגים המרכזיים (כולל תוצאות מדידות, אם יש)" },
        { type: "info", text: "פרטו 2–3 אתגרים מרכזיים בפרויקט ואת הפתרון שהצעתם לכל אחד:" },
        { type: "textarea", id: "p3_ch1", label: "אתגר מרכזי 1" },
        { type: "textarea", id: "p3_sol1", label: "הפתרון שהוצע לאתגר 1" },
        { type: "textarea", id: "p3_ch2", label: "אתגר מרכזי 2" },
        { type: "textarea", id: "p3_sol2", label: "הפתרון שהוצע לאתגר 2" },
        { type: "textarea", id: "p3_ch3", label: "אתגר מרכזי 3 (אופציונלי)" },
        { type: "textarea", id: "p3_sol3", label: "הפתרון שהוצע לאתגר 3 (אופציונלי)" },

        { type: "section", label: "סיכום ניסיון וסוגי פרויקטים" },
        { type: "checkboxes", id: "expertiseAreas", label: "תחומי התמחות שהוכחת בפרויקטים (סמנו):", other: true, options: ["ניהול אסטרטגי","שיפור תהליכים","ניהול שינוי","משאבי אנוש","פיננסים וכלכלה","שיווק ומכירות","טכנולוגיה ודיגיטל"] },
        { type: "checkboxes", id: "orgTypes", label: "סוגי ארגונים שעבדת איתם (סמנו):", other: true, options: ["סטארט-אפים ועסקים קטנים","חברות בינוניות","תאגידים גדולים","מגזר ציבורי","מלכ\"רים"] },
        { type: "textarea", id: "proudest", label: "הישג מקצועי שאתה/את הכי גאה בו" },
        { type: "section", label: "הצהרה" },
        { type: "info", text: "אני החתום/ה מטה מצהיר/ה כי המידע שמסרתי בטופס זה נכון, מדויק ומשקף פרויקטים בייעוץ שביצעתי באופן אישי או שבהם היה לי חלק מקצועי מהותי, בהתאם לתפקידי כמפורט בטופס.\n\nאני מצהיר/ה כי במסגרת תיאור הפרויקטים הקפדתי לשמור על סודיות הלקוחות, על סודות מסחריים ועל מידע עסקי רגיש, וכי השמטתי כל פרט מזהה או פרט העלול, במישרין או בעקיפין, להביא לזיהוי הלקוח, עובדיו, ספקיו, לקוחותיו או כל גורם אחר הקשור בפרויקט.\n\nאני מצהיר/ה כי לא כללתי בטופס מידע אישי, מידע רגיש או מידע החוסה תחת הגנת חוק הגנת הפרטיות, התשמ\"א–1981, אלא אם הוא הוצג באופן כללי, מצומצם ובלתי מזהה, כנדרש לצורך הצגת ניסיוני המקצועי בלבד.\n\nידוע לי כי האחריות לשמירה על סודיות, על פרטיות ועל אי-חשיפת מידע מזהה חלה עליי, וכי מסירת מידע חסוי, מידע אישי או מידע שעלול לזהות לקוח או צד שלישי, עלולה להוות הפרה של חובותיי המקצועיות, האתיות והחוקיות.\n\nאני מאשר/ת כי הפרויקטים שתוארו בטופס מייצגים את ניסיוני המקצועי האישי, וכי הם נמסרו למטרת בחינת כשירותי המקצועית במסגרת תהליך ההסמכה בלבד." }
      ]
    }
  ]
};
