// ===================================================================
//  הגדרות האפליקציה  —  ניתן לעריכה בלי ידע בתכנות
// ===================================================================
window.APP_CONFIG = {

  // כתובות המייל של חברי הוועדה שיקבלו גישת ניהול (רואים את כל המשתתפים).
  // יש להקפיד על אותיות קטנות.
  adminEmails: [
    "jude@excelleader.co.il"
  ],

  // תבניות להורדה. הקבצים יושבים בתיקייה templates/ של האפליקציה.
  templates: [
    { file: "תבנית דוח אבחון מקצועי.docx", title: "תבנית דוח אבחון מקצועי", desc: "מבנה דוח אבחון לדוגמה" },
    { file: "תבנית דוח המלצות מקצועי.docx", title: "תבנית דוח המלצות מקצועי", desc: "מבנה דוח המלצות לדוגמה" },
    { file: "תבנית תיאור פרויקט ייעוץ.docx", title: "תבנית תיאור פרויקט ייעוץ", desc: "לתיאור פרויקטים מייצגים" },
    { file: "מה צריכה להכיל תכנית עסקית.docx", title: "מה צריכה להכיל תכנית עסקית", desc: "מבנה תכנית עסקית" },
    { file: "מדריך Best Practice ליועץ עסקי.pdf", title: "מדריך Best Practice ליועץ עסקי", desc: "חומר עזר מלא (PDF)" }
  ],

  // מסמכים שהמשתתף נדרש להעלות (רשימת תיוג).
  requiredUploads: [
    { id: "cv", title: "קורות חיים מפורטים", short: "קו״ח", desc: "כולל תיאורי פרויקטים להוכחת ניסיון ומומחיות" },
    { id: "diagnosis", title: "דוגמת דוח אבחון מקצועי", short: "דוח אבחון", desc: "מבנה עקרוני של דוח אבחון" },
    { id: "recommendations", title: "דוגמת דוח המלצות מקצועי", short: "דוח המלצות", desc: "מבנה עקרוני של דוח המלצות" },
    { id: "projects", title: "תיאור פרויקטים מייצגים", short: "פרויקטים", desc: "לפי תבנית תיאור פרויקט ייעוץ" },
    { id: "clientRefs", title: "המלצות לקוחות", short: "המלצות", desc: "מכתבי המלצה או פרטי ממליצים" }
  ],

  // טפסים שממלאים וחותמים בתוך האפליקציה.
  forms: [
    {
      id: "declaration",
      title: "כתב התחייבות ליישום קוד המקצוע",
      short: "התחייבות",
      subtitle: "לחתימה בתום הדרכת ההסמכה",
      intro: "אני הח״מ מצהיר/ה ומתחייב/ת בזאת, מרצוני החופשי, כי איישם בעבודתי השוטפת את עקרונות התקן וקוד המקצוע של לשכת היועצים העסקיים והניהוליים בישראל, כמפורט להלן:",
      fields: [
        { id: "fullName", label: "שם מלא", type: "text", required: true },
        { id: "idNumber", label: "מספר תעודת זהות", type: "text", required: true },
        { id: "certNumber", label: "מספר הסמכה (אם ידוע)", type: "text", required: false }
      ],
      commitments: [
        "אפעל על-פי קוד המקצוע לייעוץ העסקי-ניהולי של הלשכה, ואיישם את עקרונותיו בכל התקשרות מקצועית.",
        "אנהל את תהליך הייעוץ בהתאם לשלבי תקן ISO 20700 (התקשרות, ביצוע וסגירה), תוך הבנת הקשר הלקוח, ניהול סיכונים ויצירת ערך.",
        "אעמיד את טובת הלקוח ואת יצירת הערך המדיד ובר-הקיימא במרכז עבודתי.",
        "אשמור על התנהגות אתית, יושרה, אובייקטיביות ואי-תלות מקצועית.",
        "אשמור על סודיות מידע הלקוח, על הגנת הפרטיות ועל קניין רוחני, אגלה כל ניגוד עניינים אפשרי ואמנע ממנו.",
        "אגדיר בבירור מול הלקוח את היקף העבודה, המטרות, המתודולוגיה, התנאים והתוצרים בכל התקשרות.",
        "אקיים תקשורת שקופה, כנה ואפקטיבית עם הלקוח ועם בעלי העניין לאורך הפרויקט.",
        "אבסס את המלצותיי על נתונים, ניתוח מקצועי ושיקול דעת ענייני.",
        "אתמיד בפיתוח מקצועי מתמשך (CPD) ובעדכון שוטף של הידע, הכלים והמתודולוגיות שלי.",
        "אפעל בהתאם לתקנון, לכללי האתיקה ולערכי הלשכה, ואשמור על כבוד המקצוע ומעמדו."
      ],
      confirmText: "קראתי את ההתחייבויות לעיל ואני מתחייב/ת לפעול לפיהן.",
      closing: "ידוע לי כי יישום עקרונות הקוד הוא תנאי לקבלת ההסמכה ולשמירתה.",
      requireSignature: true
    },

    {
      id: "selfAssessCompetence",
      title: "הערכה עצמית לפי מסגרת הכשירויות IBCA",
      short: "הע׳ כשירויות",
      subtitle: "דרגו את עצמכם בכל כישור. ניתן לשמור ולעדכן בכל עת.",
      requireSignature: true,
      confirmText: "מילאתי את הטופס בכנות, ההערכה משקפת את יכולותיי הנוכחיות, ואני מחויב/ת להתפתחות מקצועית מתמשכת ולעבודה לפי תקנים מקצועיים.",
      items: [
        { type: "info", text: "סולם הדירוג: 1 בסיסי · 2 מתחיל · 3 בינוני · 4 מתקדם · 5 מומחה · 0 לא מכיר כלל. ענו בכנות, זה יעזור לזהות תחומי פיתוח." },
        { type: "section", label: "פרטים אישיים" },
        { type: "text", id: "fullName", label: "שם מלא", required: true },
        { type: "text", id: "yearsExp", label: "שנות ניסיון בייעוץ" },
        { type: "text", id: "specialty", label: "תחום התמחות עיקרי" },
        { type: "section", label: "1. הבנה עסקית" },
        { type: "section", level: 3, label: "1.1 ידע מקצועי בתחומי הניהול" },
        { type: "checkboxes", id: "mgmtAreas", label: "תחומי ידע מרכזיים (סמנו את שלכם):", other: true, options: ["ניהול אסטרטגי","ניהול משאבי אנוש","ניהול פיננסי","ניהול שיווק ומכירות","ניהול תפעול","ניהול טכנולוגיה","ניהול סיכונים","ניהול לוגיסטי","ניהול מערכות מידע","ניהול מערכות תקינה"] },
        { type: "section", level: 3, label: "1.2 הבנה ארגונית" },
        { type: "rating", id: "orgStructure", label: "ניתוח מבנה ארגוני" },
        { type: "rating", id: "orgCulture", label: "הבנת תרבות ארגונית" },
        { type: "rating", id: "powerDynamics", label: "זיהוי דינמיקות כוח" },
        { type: "rating", id: "decisionMaking", label: "הבנת תהליכי קבלת החלטות" },
        { type: "textarea", id: "orgExample", label: "דוגמה מפרויקט שבו ניתחתם ארגון" },
        { type: "section", level: 3, label: "1.3 הבנה שיווקית" },
        { type: "checkboxes", id: "marketingAreas", label: "תחומי יכולת (סמנו):", options: ["ניתוח שוק ותחרות","פילוח לקוחות","אסטרטגיות שיווק","ניתוח התנהגות צרכנים","שיווק דיגיטלי","מחקר שוק"] },
        { type: "textarea", id: "marketingExample", label: "איך השתמשתם בידע שיווקי בפרויקט ייעוץ" },
        { type: "section", level: 3, label: "1.4 חשיבה אסטרטגית" },
        { type: "rating", id: "longTerm", label: "ראייה ארוכת טווח" },
        { type: "rating", id: "systemic", label: "חשיבה מערכתית" },
        { type: "rating", id: "oppThreats", label: "זיהוי הזדמנויות ואיומים" },
        { type: "rating", id: "deepAnalysis", label: "יכולת ניתוח מעמיק" },
        { type: "rating", id: "creativeThink", label: "חשיבה יצירתית" },
        { type: "textarea", id: "strategicExample", label: "תארו פרויקט שדרש חשיבה אסטרטגית" },
        { type: "section", level: 3, label: "1.5 אוריינות פיננסית" },
        { type: "checkboxes", id: "finAreas", label: "יכולות פיננסיות (סמנו):", options: ["קריאת דוחות כספיים","ניתוח יחסים פיננסיים","הערכת השקעות (ROI, NPV)","תכנון תקציב","ניתוח עלות-תועלת","מודלים פיננסיים"] },
        { type: "textarea", id: "finExample", label: "דוגמה לשימוש בכלים פיננסיים בייעוץ" },
        { type: "section", level: 3, label: "1.6 העולם הרגולטורי" },
        { type: "checkboxes", id: "regAreas", label: "היכרות עם תחומים רגולטוריים (סמנו):", options: ["דיני עבודה","דיני חברות","רגולציה פיננסית","הגנת הצרכן","דיני התחרות (הגבלים עסקיים)","הגנת הפרטיות (GDPR)","תקנות איכות סביבה","תקני איכות (ISO, HACCP)","תקני סייבר","תקני הפצת מידע","FDA / CE / משרד הבריאות / תקני מזון"] },
        { type: "textarea", id: "regExample", label: "איך התמודדתם עם סוגיה רגולטורית בפרויקט" },
        { type: "section", label: "2. מיומנויות ייעוץ" },
        { type: "section", level: 3, label: "2.1 ניתוח בעיות" },
        { type: "checkboxes", id: "analysisTools", label: "כלי ניתוח שאתם משתמשים בהם (סמנו):", other: true, options: ["5 Whys","Root Cause Analysis","Fishbone Diagram","SWOT","Porter's 5 Forces","Value Chain Analysis","Gap Analysis"] },
        { type: "textarea", id: "problemExample", label: "תארו בעיה מורכבת שפתרתם ואיך" },
        { type: "section", level: 3, label: "2.2 פיתוח פתרונות" },
        { type: "rating", id: "creativity2", label: "חשיבה יצירתית" },
        { type: "rating", id: "alternatives", label: "פיתוח אלטרנטיבות" },
        { type: "rating", id: "feasibility", label: "הערכת כדאיות" },
        { type: "rating", id: "orgFit", label: "התאמה לארגון" },
        { type: "rating", id: "implementationCap", label: "יכולת יישום" },
        { type: "textarea", id: "solutionExample", label: "דוגמה לפתרון חדשני שפיתחתם" },
        { type: "section", level: 3, label: "2.3 ניהול פרויקטים" },
        { type: "checkboxes", id: "pmTools", label: "כלי ושיטות ניהול פרויקטים (סמנו):", other: true, options: ["MS Project / Asana / Monday","Gantt Charts","PERT/CPM","Agile/Scrum","Risk Management","Stakeholder Management"] },
        { type: "text", id: "bigProjBudget", label: "הפרויקט הגדול ביותר שניהלתם — תקציב (ש\"ח)" },
        { type: "text", id: "bigProjDuration", label: "משך (חודשים)" },
        { type: "text", id: "bigProjTeam", label: "גודל צוות (אנשים)" },
        { type: "textarea", id: "bigProjDesc", label: "תיאור קצר" },
        { type: "section", level: 3, label: "2.4 ניהול שינויים" },
        { type: "checkboxes", id: "changeModels", label: "מודלי ניהול שינוי שאתם מכירים (סמנו):", other: true, options: ["Kotter's 8 Steps","ADKAR","Lean Change Management","Bridges Transition Model","McKinsey 7-S"] },
        { type: "textarea", id: "changeExample", label: "תארו תהליך שינוי מאתגר שהובלתם" },
        { type: "section", label: "3. מיומנויות בין-אישיות" },
        { type: "section", level: 3, label: "3.1 תקשורת" },
        { type: "rating", id: "presenting", label: "הצגה בפני קהל" },
        { type: "rating", id: "writing", label: "כתיבה מקצועית" },
        { type: "rating", id: "listening", label: "הקשבה פעילה" },
        { type: "rating", id: "nonverbal", label: "תקשורת לא מילולית" },
        { type: "rating", id: "simplify", label: "הסבר מורכבות בפשטות" },
        { type: "textarea", id: "presentingChallenge", label: "ההצגה הכי מאתגרת שעשיתם" },
        { type: "section", level: 3, label: "3.2 בניית מערכות יחסים" },
        { type: "rating", id: "trust", label: "בניית אמון מהיר" },
        { type: "rating", id: "networks", label: "רשתות מקצועיות" },
        { type: "rating", id: "longRelations", label: "ניהול קשרים ארוכי טווח" },
        { type: "rating", id: "seniors", label: "עבודה עם דרגים בכירים" },
        { type: "section", level: 3, label: "3.3 הנחיה ואימון" },
        { type: "checkboxes", id: "coachingExp", label: "ניסיון בהנחיה (סמנו):", options: ["הנחיית סדנאות","אימון מנהלים","הקמת צוותים","פיתוח עובדים","הכשרות מקצועיות"] },
        { type: "text", id: "coachedCount", label: "כמה אנשים אימנתם/הנחיתם בשנה האחרונה" },
        { type: "section", label: "4. תכונות אישיות" },
        { type: "section", level: 3, label: "4.1 יושרה ואתיקה" },
        { type: "textarea", id: "ethicsHandling", label: "איך אתם מטפלים בדילמות אתיות" },
        { type: "textarea", id: "principlesStood", label: "תארו מצב שבו עמדתם על העקרונות שלכם" },
        { type: "section", level: 3, label: "4.2 למידה מתמשכת" },
        { type: "checkboxes", id: "learningActivities", label: "פעילויות למידה בשנה האחרונה (סמנו):", options: ["קורסים מקצועיים","כנסים ואירועים","קריאה מקצועית","הסמכות חדשות","למידה עצמית"] },
        { type: "section", level: 3, label: "4.3 יכולת הסתגלות" },
        { type: "rating", id: "adaptability", label: "יכולת הסתגלות" },
        { type: "textarea", id: "adaptExample", label: "תארו מצב שבו נדרשתם להסתגל במהירות" },
        { type: "section", label: "5. מומחיות טכנית" },
        { type: "section", level: 3, label: "5.1 התמחות רלוונטית" },
        { type: "text", id: "mainField", label: "התחום הראשי שלכם" },
        { type: "text", id: "yearsInField", label: "שנות ניסיון בתחום" },
        { type: "rating", id: "expertiseLevel", label: "רמת המומחיות" },
        { type: "textarea", id: "fieldAchievements", label: "הישגים מרכזיים בתחום ההתמחות" },
        { type: "section", level: 3, label: "5.2 כלים ומתודולוגיות אנליטיים" },
        { type: "rating", id: "excelAdv", label: "Excel מתקדם" },
        { type: "rating", id: "biTools", label: "כלי BI (Tableau, PowerBI)" },
        { type: "rating", id: "processMapping", label: "Process Mapping" },
        { type: "rating", id: "dataMining", label: "Data Mining" },
        { type: "section", level: 3, label: "5.3 מודעות טכנולוגית" },
        { type: "checkboxes", id: "techAreas", label: "תחומי טכנולוגיה שאתם מכירים (סמנו):", options: ["Digital Transformation","Cloud Computing","AI & Machine Learning","Automation/RPA","Cybersecurity","IoT","Blockchain"] },
        { type: "section", level: 3, label: "5.4 חדשנות ויצירתיות" },
        { type: "textarea", id: "innovationExamples", label: "דוגמאות לחדשנות שהובלתם" },
        { type: "section", label: "סיכום והערכה כוללת" },
        { type: "textarea", id: "strengths", label: "5 נקודות החוזק המרכזיות שלכם" },
        { type: "textarea", id: "devAreas", label: "3 התחומים שהכי חשוב לכם לפתח" },
        { type: "textarea", id: "devPlan", label: "איך אתם מתכננים לפתח את עצמכם בשנה הקרובה" },
        { type: "rating", id: "overall10", label: "הערכת הכשירות הכוללת שלכם כיועץ מוסמך (1-10)", max: 10 },
        { type: "textarea", id: "overallReason", label: "נימוק להערכה" },
        { type: "section", label: "הצהרה" }
      ]
    },

    {
      id: "selfAssessStandards",
      title: "הערכה עצמית — יישום עקרונות התקנים הבינלאומיים",
      short: "הע׳ תקנים",
      subtitle: "דרגו את רמת היישום שלכם בכל נושא. ניתן לשמור ולעדכן בכל עת.",
      requireSignature: true,
      confirmText: "מילאתי את הטופס בכנות, אני מבין/ה את חשיבות יישום התקנים הבינלאומיים בעבודתי, ומתחייב/ת להמשיך ללמוד ולהשתפר ולפעול באחריות מקצועית וחברתית.",
      items: [
        { type: "info", text: "סולם הדירוג: 1 לא מכיר/לא משתמש · 2 מכיר תיאורטית · 3 משתמש לעיתים · 4 משתמש באופן קבוע · 5 מומחה ומיישם באופן מתקדם." },
        { type: "section", label: "פרטים אישיים" },
        { type: "text", id: "fullName", label: "שם מלא", required: true },
        { type: "text", id: "yearsExp", label: "מספר שנות ניסיון בייעוץ" },
        { type: "section", label: "חלק א': הנחיות תהליך הייעוץ המקצועי" },
        { type: "section", level: 3, label: "הבנת הקשר הלקוח" },
        { type: "rating", id: "clientContext", label: "רמת היישום" },
        { type: "checkboxes", id: "contextMethods", label: "איך אתם חוקרים את הקשר העסקי (סמנו):", other: true, options: ["ניתוח סביבת העסקים והתחרות","מיפוי בעלי עניין","בדיקת מגמות בתעשייה","ניתוח PESTLE","חקר התרבות הארגונית"] },
        { type: "textarea", id: "contextExample", label: "דוגמה לפרויקט שבו ההקשר העסקי היה קריטי" },
        { type: "section", level: 3, label: "הגדרת היקף ומטרות ברורות" },
        { type: "rating", id: "scopeDef", label: "רמת היישום" },
        { type: "checkboxes", id: "scopeTools", label: "כלים להגדרת היקף (סמנו):", options: ["חוזה עם deliverables ברורים","מטריצת RACI","Work Breakdown Structure (WBS)","קריטריוני הצלחה מדידים","לוח זמנים עם milestones","הגדרת תקציב וגבולות"] },
        { type: "textarea", id: "scopeChanges", label: "איך אתם מטפלים בשינויים בהיקף במהלך הפרויקט" },
        { type: "section", level: 3, label: "ניהול ציפיות ותקשורת" },
        { type: "rating", id: "expectations", label: "רמת היישום" },
        { type: "checkboxes", id: "expMethods", label: "שיטות ניהול ציפיות (סמנו):", options: ["דיווח שבועי סטנדרטי","פגישות סטטוס קבועות","מערכת התרעות מוקדמות","תיעוד החלטות ושינויים","מערכת פידבק דו-כיוונית"] },
        { type: "section", level: 3, label: "איסוף וניתוח מידע שיטתי" },
        { type: "rating", id: "dataCollection", label: "רמת היישום" },
        { type: "checkboxes", id: "dataMethods", label: "שיטות איסוף מידע (סמנו):", options: ["ראיונות מובנים ופתוחים","שאלונים וסקרים","ניתוח מסמכים ונתונים","תצפיות ו-shadowing","סדנאות ופוקוס גרופים","ניתוח נתונים כמותיים ואיכותיים","בנצ'מרקינג"] },
        { type: "textarea", id: "dataQuality", label: "איך אתם מבטיחים איכות ואמינות הנתונים" },
        { type: "section", level: 3, label: "שיתוף והעצמה של הלקוח" },
        { type: "rating", id: "clientEmpower", label: "רמת היישום" },
        { type: "checkboxes", id: "empowerWays", label: "דרכים לשיתוף הלקוח (סמנו):", options: ["סדנאות עבודה משותפות","הכשרה ופיתוח יכולות פנימיות","העברת כלים ומתודולוגיות","יצירת תהליכי עבודה פנימיים","מנטורינג ו-coaching","הקמת צוותי שינוי פנימיים"] },
        { type: "section", level: 3, label: "הערכת תוצאות ומדידת הצלחה" },
        { type: "rating", id: "resultsMeasure", label: "רמת היישום" },
        { type: "checkboxes", id: "successMetrics", label: "איך אתם מודדים הצלחה (סמנו):", options: ["מדדי ביצוע כמותיים (KPIs)","משוב איכותי מבעלי עניין","השוואה למצב הבסיס","מדידת ROI ותועלת עסקית","שביעות רצון לקוחות","מדידת קיימות ההשפעה"] },
        { type: "textarea", id: "successExample", label: "דוגמה למדידת הצלחה מפרויקט" },
        { type: "section", level: 3, label: "איסוף לקחים ושיפור מתמיד" },
        { type: "rating", id: "lessons", label: "רמת היישום" },
        { type: "checkboxes", id: "lessonWays", label: "איך אתם אוספים לקחים (סמנו):", options: ["פגישת סיכום עם הלקוח","רטרוספקטיבה של הצוות","ניתוח מה עבד ומה לא","תיעוד best practices","שיתוף לקחים עם עמיתים","עדכון מתודולוגיות וכלים"] },
        { type: "section", label: "חלק ב': עקרונות שיפור מתמיד (PDCA)" },
        { type: "rating", id: "plan", label: "תכנון (Plan)" },
        { type: "checkboxes", id: "planWays", label: "איך אתם מתכננים (סמנו):", options: ["הגדרת מטרות SMART","זיהוי סיכונים ותכנון התמודדות","קביעת מדדי הצלחה מראש","תכנון משאבים ולוח זמנים","הגדרת נקודות בקרה ותיקון מסלול"] },
        { type: "rating", id: "doStep", label: "ביצוע (Do)" },
        { type: "textarea", id: "doQuality", label: "איך אתם מבטיחים ביצוע איכותי" },
        { type: "rating", id: "checkStep", label: "בדיקה (Check)" },
        { type: "checkboxes", id: "checkWays", label: "שיטות בקרה ומעקב (סמנו):", options: ["דיווחי התקדמות שוטפים","מדידת KPIs","סקרי שביעות רצון ביניים","ביקורות איכות","בדיקות milestone","פידבק מבעלי עניין"] },
        { type: "rating", id: "actStep", label: "פעולה (Act)" },
        { type: "textarea", id: "actHow", label: "איך אתם מיישמים שיפורים" },
        { type: "section", label: "חלק ג': אחריות חברתית וקיימות" },
        { type: "rating", id: "stakeholderMap", label: "מיפוי בעלי עניין" },
        { type: "checkboxes", id: "stakeholders", label: "איך אתם מזהים בעלי עניין (סמנו):", options: ["עובדים בכל הרמות","לקוחות ומשתמשי קצה","ספקים ושותפים עסקיים","קהילה מקומית","משקיעים ובעלי מניות","רגולטורים וגופי פיקוח","ארגוני חברה אזרחית"] },
        { type: "rating", id: "envImpact", label: "הערכת השפעה סביבתית" },
        { type: "checkboxes", id: "envAreas", label: "איך אתם מעריכים השפעה סביבתית (סמנו):", options: ["צריכת אנרגיה ופליטות","ניצול משאבים ופסולת","השפעה על המגוון הביולוגי","מחזור וקיימות","מעבר לטכנולוגיות ירוקות","חותם פחמני"] },
        { type: "textarea", id: "envExample", label: "דוגמה לפרויקט שבו התחשבתם בהיבט הסביבתי" },
        { type: "rating", id: "socialImpact", label: "השפעה חברתית וקהילתית" },
        { type: "rating", id: "transparency", label: "שקיפות בתהליכי עבודה" },
        { type: "rating", id: "ethics", label: "התנהלות אתית" },
        { type: "textarea", id: "ethicsExample", label: "דוגמה למצב אתי מורכב שהתמודדתם איתו" },
        { type: "rating", id: "sustainability", label: "חשיבה קיימותית" },
        { type: "section", label: "חלק ד': אינטגרציה וישימות" },
        { type: "textarea", id: "integration", label: "איך אתם משלבים את כל העקרונות יחד" },
        { type: "textarea", id: "allThreeExample", label: "תארו פרויקט שבו יישמתם את שלושת התקנים (תהליך ייעוץ, שיפור מתמיד, אחריות חברתית)" },
        { type: "section", label: "חלק ה': הערכה כוללת ותכנון עתידי" },
        { type: "textarea", id: "strongestArea", label: "התחום החזק ביותר שלכם" },
        { type: "textarea", id: "weakestArea", label: "התחום שהכי צריך פיתוח" },
        { type: "rating", id: "rateConsulting", label: "תהליכי ייעוץ מקצועיים" },
        { type: "rating", id: "rateImprovement", label: "שיפור מתמיד ולמידה" },
        { type: "rating", id: "rateSocial", label: "אחריות חברתית וקיימות" },
        { type: "textarea", id: "futureGoals", label: "3 המטרות העיקריות לשיפור בשנה הקרובה" },
        { type: "section", label: "הצהרה" }
      ]
    }
  ]
};
