// ===================================================================
//  הגדרות האפליקציה  —  ניתן לעריכה בלי ידע בתכנות
// ===================================================================
window.APP_CONFIG = {

  // כתובות המייל של חברי הוועדה שיקבלו גישת ניהול (רואים את כל המשתתפים).
  // יש להקפיד על אותיות קטנות.
  adminEmails: [
    "jude@excelleader.co.il"
  ],

  // תבניות להורדה. הקבצים יושבים בתיקייה templates/ של האפליקציה.
  templates: [
    { file: "תבנית דוח אבחון מקצועי.docx", title: "תבנית דוח אבחון מקצועי", desc: "מבנה דוח אבחון לדוגמה" },
    { file: "תבנית דוח המלצות מקצועי.docx", title: "תבנית דוח המלצות מקצועי", desc: "מבנה דוח המלצות לדוגמה" },
    { file: "תבנית תיאור פרויקט ייעוץ.docx", title: "תבנית תיאור פרויקט ייעוץ", desc: "לתיאור פרויקטים מייצגים" },
    { file: "מה צריכה להכיל תכנית עסקית.docx", title: "מה צריכה להכיל תכנית עסקית", desc: "מבנה תכנית עסקית" },
    { file: "מדריך Best Practice ליועץ עסקי.pdf", title: "מדריך Best Practice ליועץ עסקי", desc: "חומר עזר מלא (PDF)" }
  ],

  // מסמכים שהמשתתף נדרש להעלות (רשימת תיוג).
  requiredUploads: [
    { id: "cv", title: "קורות חיים מפורטים", short: "קו״ח", desc: "כולל תיאורי פרויקטים להוכחת ניסיון ומומחיות" },
    { id: "diagnosis", title: "דוגמת דוח אבחון מקצועי", short: "דוח אבחון", desc: "מבנה עקרוני של דוח אבחון" },
    { id: "recommendations", title: "דוגמת דוח המלצות מקצועי", short: "דוח המלצות", desc: "מבנה עקרוני של דוח המלצות" },
    { id: "projects", title: "תיאור פרויקטים מייצגים", short: "פרויקטים", desc: "לפי תבנית תיאור פרויקט ייעוץ" },
    { id: "clientRefs", title: "המלצות לקוחות", short: "המלצות", desc: "מכתבי המלצה או פרטי ממליצים" }
  ],

  // טפסים שממלאים וחותמים בתוך האפליקציה.
  forms: [
    {
      id: "declaration",
      title: "כתב התחייבות ליישום קוד המקצוע",
      short: "התחייבות",
      subtitle: "לחתימה בתום הדרכת ההסמכה",
      intro: "אני הח״מ מצהיר/ה ומתחייב/ת בזאת, מרצוני החופשי, כי איישם בעבודתי השוטפת את עקרונות קוד מקצוע היועץ העסקי של לשכת היועצים העסקיים בישראל, כמפורט להלן:",
      fields: [
        { id: "fullName", label: "שם מלא", type: "text", required: true },
        { id: "idNumber", label: "מספר תעודת זהות", type: "text", required: true },
        { id: "certNumber", label: "מספר הסמכה (אם קיבלת בעבר)", type: "text", required: false }
      ],
      commitments: [
        "אפעל על-פי קוד מקצוע היועץ העסקי של לשכת היועצים העסקיים בישראל, ואיישם את עקרונותיו בכל התקשרות מקצועית.",
        "אנהל את תהליך הייעוץ בהתאם לקוד המקצוע (שלבי התקשרות, ביצוע וסגירה), תוך הבנת הקשר הלקוח, ניהול סיכונים ויצירת ערך.",
        "אעמיד את טובת הלקוח ואת יצירת הערך המדיד ובר-הקיימא במרכז עבודתי.",
        "אשמור על התנהגות אתית, יושרה, אובייקטיביות ואי-תלות מקצועית.",
        "אשמור על סודיות מידע הלקוח, על הגנת הפרטיות ועל קניין רוחני, אגלה כל ניגוד עניינים אפשרי ואמנע ממנו.",
        "אגדיר בבירור מול הלקוח את היקף העבודה, המטרות, המתודולוגיה, התנאים והתוצרים בכל התקשרות.",
        "אקיים תקשורת שקופה, כנה ואפקטיבית עם הלקוח ועם בעלי העניין לאורך הפרויקט.",
        "אבסס את המלצותיי על נתונים, ניתוח מקצועי ושיקול דעת ענייני.",
        "אתמיד בפיתוח מקצועי מתמשך (CPD) ובעדכון שוטף של הידע, הכלים והמתודולוגיות שלי.",
        "אפעל בהתאם לתקנון, לכללי האתיקה ולערכי הלשכה, ואשמור על כבוד המקצוע ומעמדו."
      ],
      confirmText: "קראתי את ההתחייבויות לעיל ואני מתחייב/ת לפעול לפיהן.",
      closing: "ידוע לי כי יישום עקרונות הקוד הוא תנאי לקבלת ההסמכה ולשמירתה.",
      requireSignature: true
    },

    {
      id: "selfAssessCompetence",
      title: "הערכה עצמית לפי מסגרת הכשירויות IBCA",
      short: "הע׳ כשירויות",
      subtitle: "דרגו את עצמכם בכל כישור. ניתן לשמור ולעדכן בכל עת.",
      requireSignature: true,
      confirmText: "מילאתי את הטופס בכנות, ההערכה משקפת את יכולותיי הנוכחיות, ואני מחויב/ת להתפתחות מקצועית מתמשכת ולעבודה לפי קוד המקצוע.",
      items: [
        { type: "info", text: "סולם הדירוג: 1 בסיסי · 2 מתחיל · 3 בינוני · 4 מתקדם · 5 מומחה · 0 לא מכיר כלל. ענו בכנות, זה יעזור לזהות תחומי פיתוח." },
        { type: "section", label: "פרטים אישיים" },
        { type: "text", id: "fullName", label: "שם מלא", required: true },
        { type: "text", id: "yearsExp", label: "שנות ניסיון בייעוץ" },
        { type: "text", id: "specialty", label: "תחום התמחות עיקרי" },
        { type: "section", label: "1. הבנה עסקית" },
        { type: "section", level: 3, label: "1.1 ידע מקצועי בתחומי הניהול" },
        { type: "checkboxes", id: "mgmtAreas", label: "תחומי ידע מרכזיים (סמנו את שלכם):", other: true, options: ["ניהול אסטרטגי","ניהול משאבי אנוש","ניהול פיננסי","ניהול שיווק ומכירות","ניהול תפעול","ניהול טכנולוגיה","ניהול סיכונים","ניהול לוגיסטי","ניהול מערכות מידע","ניהול מערכות תקינה","לא מכיר אף אחד מאלה"] },
        { type: "section", level: 3, label: "1.2 הבנה ארגונית" },
        { type: "rating", id: "orgStructure", label: "ניתוח מבנה ארגוני", zero: true },
        { type: "rating", id: "orgCulture", label: "הבנת תרבות ארגונית", zero: true },
        { type: "rating", id: "powerDynamics", label: "זיהוי דינמיקות כוח", zero: true },
        { type: "rating", id: "decisionMaking", label: "הבנת תהליכי קבלת החלטות", zero: true },
        { type: "textarea", id: "orgExample", label: "דוגמה מפרויקט שבו ניתחתם ארגון" },
        { type: "section", level: 3, label: "1.3 הבנה שיווקית" },
        { type: "checkboxes", id: "marketingAreas", label: "תחומי יכולת (סמנו):", other: true, options: ["ניתוח שוק ותחרות","פילוח לקוחות","אסטרטגיות שיווק","ניתוח התנהגות צרכנים","שיווק דיגיטלי","מחקר שוק","לא מכיר אף אחד מאלה"] },
        { type: "textarea", id: "marketingExample", label: "איך השתמשתם בידע שיווקי בפרויקט ייעוץ" },
        { type: "section", level: 3, label: "1.4 חשיבה אסטרטגית" },
        { type: "rating", id: "longTerm", label: "ראייה ארוכת טווח", zero: true },
        { type: "rating", id: "systemic", label: "חשיבה מערכתית", zero: true },
        { type: "rating", id: "oppThreats", label: "זיהוי הזדמנויות ואיומים", zero: true },
        { type: "rating", id: "deepAnalysis", label: "יכולת ניתוח מעמיק", zero: true },
        { type: "rating", id: "creativeThink", label: "חשיבה יצירתית", zero: true },
        { type: "textarea", id: "strategicExample", label: "תארו פרויקט שדרש חשיבה אסטרטגית" },
        { type: "section", level: 3, label: "1.5 אוריינות פיננסית" },
        { type: "checkboxes", id: "finAreas", label: "יכולות פיננסיות (סמנו):", other: true, options: ["קריאת דוחות כספיים","ניתוח יחסים פיננסיים","הערכת השקעות (ROI, NPV)","תכנון תקציב","ניתוח עלות-תועלת","מודלים פיננסיים","לא מכיר אף אחד מאלה"] },
        { type: "textarea", id: "finExample", label: "דוגמה לשימוש בכלים פיננסיים בייעוץ" },
        { type: "section", level: 3, label: "1.6 העולם הרגולטורי" },
        { type: "checkboxes", id: "regAreas", label: "היכרות עם תחומים רגולטוריים (סמנו):", other: true, options: ["דיני עבודה","דיני חברות","רגולציה פיננסית","הגנת הצרכן","דיני התחרות (הגבלים עסקיים)","הגנת הפרטיות (GDPR)","תקנות איכות סביבה","תקני איכות (ISO, HACCP)","תקני סייבר","תקני הפצת מידע","FDA / CE / משרד הבריאות / תקני מזון","לא מכיר אף אחד מאלה"] },
        { type: "textarea", id: "regExample", label: "איך התמודדתם עם סוגיה רגולטורית בפרויקט" },
        { type: "section", label: "2. מיומנויות ייעוץ" },
        { type: "section", level: 3, label: "2.1 ניתוח בעיות" },
        { type: "checkboxes", id: "analysisTools", label: "כלי ניתוח שאתם משתמשים בהם (סמנו):", other: true, options: ["5 Whys","Root Cause Analysis","Fishbone Diagram","SWOT","Porter's 5 Forces","Value Chain Analysis","Gap Analysis","לא מכיר אף אחד מאלה"] },
        { type: "textarea", id: "problemExample", label: "תארו בעיה מורכבת שפתרתם ואיך" },
        { type: "section", level: 3, label: "2.2 פיתוח פתרונות" },
        { type: "rating", id: "creativity2", label: "חשיבה יצירתית", zero: true },
        { type: "rating", id: "alternatives", label: "פיתוח אלטרנטיבות", zero: true },
        { type: "rating", id: "feasibility", label: "הערכת כדאיות", zero: true },
        { type: "rating", id: "orgFit", label: "התאמה לארגון", zero: true },
        { type: "rating", id: "implementationCap", label: "יכולת יישום", zero: true },
        { type: "textarea", id: "solutionExample", label: "דוגמה לפתרון חדשני שפיתחתם" },
        { type: "section", level: 3, label: "2.3 ניהול פרויקטים" },
        { type: "checkboxes", id: "pmTools", label: "כלי ושיטות ניהול פרויקטים (סמנו):", other: true, options: ["MS Project / Asana / Monday","Gantt Charts","PERT/CPM","Agile/Scrum","Risk Management","Stakeholder Management","לא מכיר אף אחד מאלה"] },
        { type: "text", id: "bigProjBudget", label: "הפרויקט הגדול ביותר שניהלתם — תקציב (ש\"ח)" },
        { type: "text", id: "bigProjDuration", label: "משך (חודשים)" },
        { type: "text", id: "bigProjTeam", label: "גודל צוות (אנשים)" },
        { type: "textarea", id: "bigProjDesc", label: "תיאור קצר" },
        { type: "section", level: 3, label: "2.4 ניהול שינויים" },
        { type: "checkboxes", id: "changeModels", label: "מודלי ניהול שינוי שאתם מכירים (סמנו):", other: true, options: ["Kotter's 8 Steps","ADKAR","Lean Change Management","Bridges Transition Model","McKinsey 7-S","לא מכיר אף אחד מאלה"] },
        { type: "textarea", id: "changeExample", label: "תארו תהליך שינוי מאתגר שהובלתם" },
        { type: "section", label: "3. מיומנויות בין-אישיות" },
        { type: "section", level: 3, label: "3.1 תקשורת" },
        { type: "rating", id: "presenting", label: "הצגה בפני קהל", zero: true },
        { type: "rating", id: "writing", label: "כתיבה מקצועית", zero: true },
        { type: "rating", id: "listening", label: "הקשבה פעילה", zero: true },
        { type: "rating", id: "nonverbal", label: "תקשורת לא מילולית", zero: true },
        { type: "rating", id: "simplify", label: "הסבר מורכבות בפשטות", zero: true },
        { type: "textarea", id: "presentingChallenge", label: "ההצגה הכי מאתגרת שעשיתם" },
        { type: "section", level: 3, label: "3.2 בניית מערכות יחסים" },
        { type: "rating", id: "trust", label: "בניית אמון מהיר", zero: true },
        { type: "rating", id: "networks", label: "רשתות מקצועיות", zero: true },
        { type: "rating", id: "longRelations", label: "ניהול קשרים ארוכי טווח", zero: true },
        { type: "rating", id: "seniors", label: "עבודה עם דרגים בכירים", zero: true },
        { type: "section", level: 3, label: "3.3 הנחיה ואימון" },
        { type: "checkboxes", id: "coachingExp", label: "ניסיון בהנחיה (סמנו):", other: true, options: ["הנחיית סדנאות","אימון מנהלים","הקמת צוותים","פיתוח עובדים","הכשרות מקצועיות"] },
        { type: "text", id: "coachedCount", label: "כמה אנשים אימנתם/הנחיתם בשנה האחרונה" },
        { type: "section", label: "4. תכונות אישיות" },
        { type: "section", level: 3, label: "4.1 יושרה ואתיקה" },
        { type: "textarea", id: "ethicsHandling", label: "איך אתם מטפלים בדילמות אתיות" },
        { type: "textarea", id: "principlesStood", label: "תארו מצב שבו עמדתם על העקרונות שלכם" },
        { type: "section", level: 3, label: "4.2 למידה מתמשכת" },
        { type: "checkboxes", id: "learningActivities", label: "פעילויות למידה בשנה האחרונה (סמנו):", other: true, options: ["קורסים מקצועיים","כנסים ואירועים","קריאה מקצועית","הסמכות חדשות","למידה עצמית"] },
        { type: "section", level: 3, label: "4.3 יכולת הסתגלות" },
        { type: "rating", id: "adaptability", label: "יכולת הסתגלות", zero: true },
        { type: "textarea", id: "adaptExample", label: "תארו מצב שבו נדרשתם להסתגל במהירות" },
        { type: "section", label: "5. מומחיות טכנית" },
        { type: "section", level: 3, label: "5.1 התמחות רלוונטית" },
        { type: "text", id: "mainField", label: "התחום הראשי שלכם" },
        { type: "text", id: "yearsInField", label: "שנות ניסיון בתחום" },
        { type: "rating", id: "expertiseLevel", label: "רמת המומחיות", zero: true },
        { type: "textarea", id: "fieldAchievements", label: "הישגים מרכזיים בתחום ההתמחות" },
        { type: "section", level: 3, label: "5.2 כלים ומתודולוגיות אנליטיים" },
        { type: "rating", id: "excelAdv", label: "Excel מתקדם", zero: true },
        { type: "rating", id: "biTools", label: "כלי BI (Tableau, PowerBI)", zero: true },
        { type: "rating", id: "processMapping", label: "Process Mapping", zero: true },
        { type: "rating", id: "dataMining", label: "Data Mining", zero: true },
        { type: "section", level: 3, label: "5.3 מודעות טכנולוגית" },
        { type: "checkboxes", id: "techAreas", label: "תחומי טכנולוגיה שאתם מכירים (סמנו):", other: true, options: ["Digital Transformation","Cloud Computing","AI & Machine Learning","Automation/RPA","Cybersecurity","IoT","Blockchain","לא מכיר אף אחד מאלה"] },
        { type: "section", level: 3, label: "5.4 חדשנות ויצירתיות" },
        { type: "textarea", id: "innovationExamples", label: "דוגמאות לחדשנות שהובלתם" },
        { type: "section", label: "סיכום והערכה כוללת" },
        { type: "textarea", id: "strengths", label: "5 נקודות החוזק המרכזיות שלכם" },
        { type: "textarea", id: "devAreas", label: "3 התחומים שהכי חשוב לכם לפתח" },
        { type: "textarea", id: "devPlan", label: "איך אתם מתכננים לפתח את עצמכם בשנה הקרובה" },
        { type: "rating", id: "overall10", label: "הערכת הכשירות הכוללת שלכם כיועץ מוסמך (1-10)", max: 10 },
        { type: "textarea", id: "overallReason", label: "נימוק להערכה" },
        { type: "section", label: "הצהרה" }
      ]
    },

    {
      id: "processUnderstanding",
      title: "אישור הבנת תהליכי העבודה לפי קוד המקצוע",
      short: "תהליכי העבודה",
      subtitle: "לקריאה ולאישור הבנה",
      requireSignature: true,
      confirmText: "קראתי והבנתי את תהליכי העבודה לפי קוד המקצוע, ואני מתחייב/ת לפעול לפיהם.",
      items: [
        { type: "info", text: "טופס זה מציג את תהליכי העבודה של היועץ לפי קוד המקצוע. אנא קראו בעיון, אשרו את הבנתכם וחתמו." },
        { type: "section", label: "פרטים אישיים" },
        { type: "text", id: "fullName", label: "שם מלא", required: true },
        { type: "section", label: "1. שלב ההתקשרות" },
        { type: "section", level: 3, label: "הבנת הקשר הלקוח" },
        { type: "statement", text: "ניתוח סביבת העסק, השוק והתחרות." },
        { type: "statement", text: "זיהוי בעלי העניין והערכת מידת השפעתם." },
        { type: "statement", text: "הערכת צרכי הלקוח וציפיותיו." },
        { type: "section", level: 3, label: "הצעה והסכם עבודה" },
        { type: "statement", text: "הגדרת היקף העבודה ומטרות מדידות." },
        { type: "statement", text: "תיאור המתודולוגיה והגישה." },
        { type: "statement", text: "קביעת תנאים והגבלות." },
        { type: "statement", text: "התייחסות להגנת הפרטיות, לקניין רוחני ולשמירה על סודיות." },
        { type: "section", label: "2. שלב הביצוע" },
        { type: "section", level: 3, label: "תכנון הפעילות" },
        { type: "statement", text: "פיתוח תכנית פרויקט מפורטת." },
        { type: "statement", text: "הקצאת משאבים, כולל צרכים פיננסיים וכוח אדם." },
        { type: "statement", text: "זיהוי סיכונים ותכנון דרכי התמודדות." },
        { type: "section", level: 3, label: "יישום" },
        { type: "statement", text: "איסוף וניתוח מידע באופן שיטתי, אובייקטיבי ובלתי תלוי." },
        { type: "statement", text: "פיתוח פתרונות מבוססי נתונים והמלצות מתועדפות." },
        { type: "statement", text: "תקשורת שוטפת ושקופה וניהול בעלי העניין." },
        { type: "statement", text: "מעקב אחר ההתקדמות ועדכון לפי הצורך." },
        { type: "section", label: "3. שלב הסגירה" },
        { type: "statement", text: "מדידת תוצאות והערכת השגת היעדים." },
        { type: "statement", text: "הפקת לקחים ותיעודם." },
        { type: "statement", text: "העברת ידע ללקוח והבטחת המשכיות ללא תלות ביועץ." },
        { type: "statement", text: "סיכום הפעילות מול הלקוח." }
      ]
    }
  ]
};
